### PR TITLE
bump semver dependency to 5.7.2 to resolve ReDoS CVE

### PR DESCRIPTION
**Pull request by ChrisdeWolf**
bump semver dependency to 5.7.2 to resolve ReDoS CVE (https://security.snyk.io/package/npm/semver).

`npm run test` passes without errors.

### CODE REVIEW

**Review by twolfson — CHANGES_REQUESTED** [review]
Thanks for the PR, it's much appreciated!
Unfortunately, it seems to deviate quite strongly from the norms from this repo.
Can you remove adding `package-lock.json` and stick to `~` for package upgrades? (`pixelsmith` is an exclusion because I maintain it)

**Comment by ChrisdeWolf** [comment]
Sure thing, thanks for the quick response. Didnt even realize the deviations from repo standards - PR updated.

p.s. should i add package-lock to .gitignore?

**Review by twolfson — APPROVED** [review]
Looks great, thanks!

**Comment by twolfson** [comment]
This has been released in `3.5.0`, and changes should auto-propagate to `gulp.spritesmith` and `grunt-spritesmith`. Thanks for the PR!

**Pull request merged**
