### PR TITLE
docs: Added Typescript definitions

### LINKED ISSUE #89: Typescript support
Hi, could you add typescript definitions in your project?

It would be helpful for us typescript users, thanks !

### PR DESCRIPTION
**Pull request by Zenoo**
This should fix #89.

I was unable to test it further, as the `npm i` command fails locally, but everything should work fine, I'll let you check.

### CODE REVIEW

**Comment by twolfson** [comment]
Wonderful! Thank you for your work on this! I'm limited on time right now, but hopefully coming into a gap tonight or this weekend. Worst case, this will be landed in 1 month (long range, I know).

**Comment by twolfson** [comment]
I started looking into TypeScript publishing conventions, and am realizing that since I don't write TypeScript regularly, then I'm not going to be able to accurately update the definition during future releases.

It looks like there's an option to maintain a `@types` repo. Would you be interested in creating one of those instead?

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by twolfson** [comment]
It does look like people even wrote one for `gulp.spritesmith` already =D

https://www.npmjs.com/package/@types/gulp.spritesmith

**Comment by Zenoo** [comment]
Alright, I'll create the types declaration on DefinitlyTyped instead.

**Comment by twolfson** [comment]
:raised_hands: Thank you!!

**Pull request closed without merging**
